import React from "react";
// import resdata from "../constants/mockData"; //default import

const resdata = [
  {
    id: "643183",
    name: "Chinese Wok",
    cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
    locality: "Venkateswara Colony",
    areaName: "Uppal",
    costForTwo: "₹250 for two",
    cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
    avgRating: 3.9,
    parentId: "61955",
    avgRatingString: "3.9",
    totalRatingsString: "500+",
  },
  {
    id: "824712",
    name: "Taaza Tiffins",
    cloudinaryImageId: "202a58344f374dd8167e58df9b30d7a4",
    locality: "Uppal",
    areaName: "Narapally",
    costForTwo: "₹200 for two",
    cuisines: ["South Indian", "Beverages", "Tiffins"],
    avgRating: 4.2,
    parentId: "232777",
    avgRatingString: "4.2",
    totalRatingsString: "100+",
  },
  {
    id: "712622",
    name: "Tulips - Oak Bean",
    cloudinaryImageId: "a7c984c4681b9c53ec6caab27e36387a",
    locality: "Annojiguda Village",
    areaName: "Pocharam",
    costForTwo: "₹300 for two",
    cuisines: ["Indian", "South Indian", "Beverages", "Juices"],
    avgRating: 4.5,
    parentId: "473602",
    avgRatingString: "4.5",
    totalRatingsString: "1K+",
  },
  {
    id: "302792",
    name: "Sri Rama Dosa Darbar",
    cloudinaryImageId: "ibhpaja03xkgkjwfdsxn",
    locality: "Uppal",
    areaName: "Uppal",
    costForTwo: "₹100 for two",
    cuisines: ["South Indian"],
    avgRating: 4.3,
    veg: true,
    parentId: "19357",
    avgRatingString: "4.3",
    totalRatingsString: "1K+",
  },
  {
    id: "58575",
    name: "Sri Gayathri Tiffins",
    cloudinaryImageId: "v2ytojzkgm1jfrki7xna",
    locality: "Vijayapuri colony",
    areaName: "Uppal",
    costForTwo: "₹100 for two",
    cuisines: ["South Indian"],
    avgRating: 4.4,
    veg: true,
    parentId: "19838",
    avgRatingString: "4.4",
    totalRatingsString: "5K+",
  },
  {
    id: "168094",
    name: "Raghavendra Tiffins",
    cloudinaryImageId: "dzofmslsngxjz5su3h47",
    locality: "Raghavendra Nagar Colony",
    areaName: "Boduppal",
    costForTwo: "₹150 for two",
    cuisines: ["South Indian"],
    avgRating: 4.3,
    veg: true,
    parentId: "19685",
    avgRatingString: "4.3",
    totalRatingsString: "5K+",
  },
  {
    id: "114341",
    name: "Faasos - Wraps, Rolls & Shawarma",
    cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
    areaName: "Boduppal",
    costForTwo: "₹200 for two",
    cuisines: ["Kebabs", "Fast Food", "Snacks", "American"],
    avgRating: 3.8,
    avgRatingString: "3.8",
  },
  {
    id: "408179",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Budda nagar colony",
    areaName: "Uppal",
    costForTwo: "₹300 for two",
    cuisines: ["Pizzas"],
    avgRating: 4.1,
    parentId: "721",
    avgRatingString: "4.1",
    totalRatingsString: "1K+",
  },
  {
    id: "362225",
    name: "Natural Ice Cream",
    cloudinaryImageId: "f5vbbvj4yrvlstwz9jzg",
    locality: "Boduppal FC",
    areaName: "Boduppal",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.4,
    veg: true,
    parentId: "2093",
    avgRatingString: "4.4",
  },
  {
    id: "114343",
    name: "Behrouz Biryani",
    cloudinaryImageId: "a4ffed13eb197c6df43dfe1c756560e5",
    locality: "PEERZADIGUDA",
    areaName: "Boduppal",
    costForTwo: "₹500 for two",
    cuisines: [
      "Biryani",
      "Kebabs",
      "Mughlai",
      "Lucknowi",
      "Hyderabadi",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4,
    parentId: "1803",
    avgRatingString: "4.0",
    totalRatingsString: "1K+",
  },
  {
    id: "446670",
    name: "Pista House Tea",
    cloudinaryImageId: "fgdpytbxlousdowe8zuz",
    locality: "Zahid Nagar",
    areaName: "Uppal",
    costForTwo: "₹100 for two",
    cuisines: ["Beverages"],
    avgRating: 4.6,
    parentId: "236815",
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
  },
  {
    id: "681746",
    name: "Babai Hotel",
    cloudinaryImageId: "bbdfbf48e1b12f75b106e23076dfb58c",
    locality: "Krishna  Nagar Colony",
    areaName: "Tarnaka, Nacharam & Malkajigiri",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian"],
    avgRating: 4.4,
    veg: true,
    parentId: "19353",
    avgRatingString: "4.4",
    totalRatingsString: "500+",
  },
  {
    id: "114348",
    name: "Sweet Truth - Cake and Desserts",
    cloudinaryImageId: "81cf6bfe2760a45a0caf2e28716ca4d7",
    locality: "PEERZADIGUDA",
    areaName: "Boduppal",
    costForTwo: "₹450 for two",
    cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
    avgRating: 4.1,
    parentId: "4444",
    avgRatingString: "4.1",
    totalRatingsString: "1K+",
  },
  {
    id: "156174",
    name: "The Good Bowl",
    cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
    locality: "Boduppal FC",
    areaName: "Boduppal",
    costForTwo: "₹400 for two",
    cuisines: [
      "Biryani",
      "North Indian",
      "Pastas",
      "Punjabi",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.1,
    parentId: "7918",
    avgRatingString: "4.1",
    totalRatingsString: "1K+",
  },
];

const Contact = () => {
  return (
    <div>
      <div>
        <input
          type="text"
          onClick={() => {
            console.log("button clicked");
          }}
        ></input>
      </div>
    </div>
  );
};

export default Contact;
